### ISSUE TITLE
Homekit does not monitor the state of the switch

### ISSUE THREAD

**Issue by santiquiss** [gand0lfi/homebridge-solidmation-switch#1]
Is there a way to monitor the state of the switch upon opening the home app? BTW, this plugin is GOLD

**Comment by santiquiss** [comment]
Actually the state of the switch always returns that it is turned off.

**Comment by gand0lfi** [comment]
The state is returned as it should. Sometimes the api does some strange things and the status isnt reflected. But it works 99% of the time. Try to close the home app and open it again.
